-- MySQL Script generated by MySQL Workbench
-- Thu Mar 20 08:55:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toolsforever
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toolsforever
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toolsforever` DEFAULT CHARACTER SET utf8 ;
USE `toolsforever` ;

-- -----------------------------------------------------
-- Table `toolsforever`.`fabriek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolsforever`.`fabriek` (
  `idfabriek` INT NOT NULL AUTO_INCREMENT,
  `naamFabriek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfabriek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolsforever`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolsforever`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `omschrijving` VARCHAR(45) NOT NULL,
  `prijs` DECIMAL(10,2) NOT NULL,
  `fabriek_idfabriek` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `fk_product_fabriek1_idx` (`fabriek_idfabriek` ASC) VISIBLE,
  CONSTRAINT `fk_product_fabriek1`
    FOREIGN KEY (`fabriek_idfabriek`)
    REFERENCES `toolsforever`.`fabriek` (`idfabriek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolsforever`.`bestellijst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolsforever`.`bestellijst` (
  `idbestellijst` INT NOT NULL AUTO_INCREMENT,
  `bestelDatum` DATE NOT NULL,
  `aantalBesteld` INT(11) NOT NULL,
  `product_idproduct` INT NOT NULL,
  `fabriek_idfabriek` INT NOT NULL,
  PRIMARY KEY (`idbestellijst`),
  INDEX `fk_bestellijst_product_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_bestellijst_fabriek1_idx` (`fabriek_idfabriek` ASC) VISIBLE,
  CONSTRAINT `fk_bestellijst_product`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `toolsforever`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bestellijst_fabriek1`
    FOREIGN KEY (`fabriek_idfabriek`)
    REFERENCES `toolsforever`.`fabriek` (`idfabriek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolsforever`.`locatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolsforever`.`locatie` (
  `idlocatie` INT NOT NULL AUTO_INCREMENT,
  `plaats` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idlocatie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolsforever`.`voorraad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolsforever`.`voorraad` (
  `idvoorraad` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `aantal` INT(11) NOT NULL,
  `inkoopprijs` DECIMAL(10,2) NOT NULL,
  `verkoopprijs` DECIMAL(10,2) NOT NULL,
  `product_idproduct` INT NOT NULL,
  `locatie_idlocatie` INT NOT NULL,
  PRIMARY KEY (`idvoorraad`),
  INDEX `fk_voorraad_product1_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_voorraad_locatie1_idx` (`locatie_idlocatie` ASC) VISIBLE,
  CONSTRAINT `fk_voorraad_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `toolsforever`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voorraad_locatie1`
    FOREIGN KEY (`locatie_idlocatie`)
    REFERENCES `toolsforever`.`locatie` (`idlocatie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
